default_install_hook_types: [pre-push]
repos:
  - repo: local
    hooks:
      - id: check
        name: check
        entry: ./check.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [pre-push]
